version: '3.8'

services:
  jasperserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=jasperuser
      - DB_PASSWORD=J@sp3r2024
      - JAVA_OPTS=-Xms1024M -Xmx2048M
    volumes:
      - jasper_data:/opt/tomcat/webapps/jasperserver
      - tomcat_logs:/opt/tomcat/logs
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jasperdb
      MYSQL_USER: jasperuser
      MYSQL_PASSWORD: J@sp3r2024
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  jasper_data:
  tomcat_logs:
  db_data:
