version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jasperserver
      MYSQL_USER: jasper
      MYSQL_PASSWORD: jasper
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat-jrs:
    build: .
    container_name: tomcat-jrs
    depends_on:
      - mysql
    ports:
      - "8888:8080"
    environment:
      DB_HOST: mysql
      DB_USER: jasper
      DB_PASS: jasper
    volumes:
      - ./default_master.properties:/opt/jasperserver/jasperreports-server-cp-8.2.0-bin/buildomatic/default_master.properties

volumes:
  mysql_data:
