version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: jrs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jasperserver
      MYSQL_USER: jasperadmin
      MYSQL_PASSWORD: jasperadmin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  jasperserver:
    build: ./jasperserver
    container_name: jrs-tomcat
    depends_on:
      - mysql
    ports:
      - "8888:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: jasperserver
      DB_USER: jasperadmin
      DB_PASSWORD: jasperadmin
    volumes:
      - jrs_webapps:/usr/local/tomcat/webapps

volumes:
  mysql_data:
  jrs_webapps:
